mv images/Acacia_Button_JE4.png images/acacia_button.png
mv images/Acacia_Door_JE5.png images/acacia_door.png
mv images/Acacia_Fence_Gate_JE3_BE2.png images/acacia_fence_gate.png
mv images/Acacia_Hanging_Sign_JE1_BE1.png images/acacia_hanging_sign.png
mv images/Acacia_Leaves.png images/acacia_leaves.png
mv images/Acacia_Planks.png images/acacia_planks.png
mv images/Acacia_Pressure_Plate_JE3_BE2.png images/acacia_pressure_plate.png
mv images/Acacia_Sapling_JE7_BE2.png images/acacia_sapling.png
mv images/Acacia_Slab.png images/acacia_slab.png
mv images/Acacia_Stairs.png images/acacia_stairs.png
mv images/Acacia_Trapdoor_JE1_BE1.png images/acacia_trapdoor.png
mv images/Acacia_Wood.png images/acacia_wood.png
mv images/Allium_JE7_BE2.png images/allium.png
mv images/Ancient_Debris_JE1_BE1.png images/ancient_debris.png
mv images/Andesite.png images/andesite.png
mv images/Andesite_Slab_JE2_BE2.png images/andesite_slab.png
mv images/Andesite_Wall_JE2_BE1.png images/andesite_wall.png
mv images/Azalea_JE2_BE2.png images/azalea.png
mv images/Azalea_Leaves.png images/azalea_leaves.png
mv images/Azure_Bluet_JE7_BE2.png images/azure_bluet.png
mv images/Bamboo_Button_JE3.png images/bamboo_button.png
mv images/Bamboo_Door_JE1.png images/bamboo_door.png
mv images/Bamboo_Fence_Gate_JE1_BE1.png images/bamboo_fence_gate.png
mv images/Bamboo_Hanging_Sign_JE1_BE1.png images/bamboo_hanging_sign.png
mv images/Bamboo_Mosaic_JE1_BE1.png images/bamboo_mosaic.png
mv images/Bamboo_Mosaic_Slab_JE1_BE1.png images/bamboo_mosaic_slab.png
mv images/Bamboo_Mosaic_Stairs_JE1_BE1.png images/bamboo_mosaic_stairs.png
mv images/Bamboo_Planks_JE2_BE2.png images/bamboo_planks.png
mv images/Bamboo_Pressure_Plate_JE2_BE2.png images/bamboo_pressure_plate.png
mv images/Bamboo_Slab_JE2_BE2.png images/bamboo_slab.png
mv images/Bamboo_Stairs_JE2.png images/bamboo_stairs.png
mv images/Bamboo_Trapdoor_JE1_BE1.png images/bamboo_trapdoor.png
mv images/Beacon_JE6_BE2.png images/beacon.png
mv images/Bedrock_JE2_BE2.png images/bedrock.png
mv images/Big_Dripleaf_JE2_BE1.png images/big_dripleaf.png
mv images/Birch_Button_JE4.png images/birch_button.png
mv images/Birch_Door_JE4.png images/birch_door.png
mv images/Birch_Fence_Gate_JE3_BE2.png images/birch_fence_gate.png
mv images/Birch_Hanging_Sign_JE1_BE1.png images/birch_hanging_sign.png
mv images/Birch_Leaves.png images/birch_leaves.png
mv images/Birch_Planks.png images/birch_planks.png
mv images/Birch_Pressure_Plate_JE3_BE2.png images/birch_pressure_plate.png
mv images/Birch_Sapling_JE7_BE2.png images/birch_sapling.png
mv images/Birch_Slab_JE3_BE2.png images/birch_slab.png
mv images/Birch_Trapdoor_JE1_BE1.png images/birch_trapdoor.png
mv images/Blackstone_JE3_BE2.png images/blackstone.png
mv images/Blackstone_Slab_JE3.png images/blackstone_slab.png
mv images/Blackstone_Stairs_JE3.png images/blackstone_stairs.png
mv images/Blackstone_Wall_JE3_BE2.png images/blackstone_wall.png
mv images/Black_Bed.png images/black_bed.png
mv images/Black_Candle.png images/black_candle.png
mv images/Black_Carpet_JE2_BE2.png images/black_carpet.png
mv images/Black_Concrete.png images/black_concrete.png
mv images/Black_Concrete_Powder.png images/black_concrete_powder.png
mv images/Black_Shulker_Box_JE2_BE2.png images/black_shulker_box.png
mv images/Black_Stained_Glass_JE3_BE3.png images/black_stained_glass.png
mv images/Black_Terracotta_JE1_BE1.png images/black_terracotta.png
mv images/Black_Wool_JE3_BE3.png images/black_wool.png
mv images/Blue_Bed.png images/blue_bed.png
mv images/Blue_Candle.png images/blue_candle.png
mv images/Blue_Carpet_JE2_BE2.png images/blue_carpet.png
mv images/Blue_Concrete.png images/blue_concrete.png
mv images/Blue_Concrete_Powder.png images/blue_concrete_powder.png
mv images/Blue_Ice_JE3_BE2.png images/blue_ice.png
mv images/Blue_Orchid_JE7_BE2.png images/blue_orchid.png
mv images/Blue_Shulker_Box_JE2_BE2.png images/blue_shulker_box.png
mv images/Blue_Stained_Glass_JE4_BE4.png images/blue_stained_glass.png
mv images/Blue_Terracotta_JE1_BE1.png images/blue_terracotta.png
mv images/Blue_Wool_JE3_BE3.png images/blue_wool.png
mv images/Bookshelf_JE4_BE2.png images/bookshelf.png
mv images/Brain_Coral_Block_JE2_BE1.png images/brain_coral_block.png
mv images/Brain_Coral_Fan_JE1_BE2.png images/brain_coral_fan.png
mv images/Brain_Coral_JE1_BE1.png images/brain_coral.png
mv images/Bricks_JE5_BE3.png images/bricks.png
mv images/Brick_Slab_JE3_BE2.png images/brick_slab.png
mv images/Brick_Wall_JE1_BE2.png images/brick_wall.png
mv images/Brown_Bed.png images/brown_bed.png
mv images/Brown_Candle.png images/brown_candle.png
mv images/Brown_Carpet_JE2_BE2.png images/brown_carpet.png
mv images/Brown_Concrete.png images/brown_concrete.png
mv images/Brown_Concrete_Powder.png images/brown_concrete_powder.png
mv images/Brown_Mushroom_JE9.png images/brown_mushroom.png
mv images/Brown_Shulker_Box_JE2_BE2.png images/brown_shulker_box.png
mv images/Brown_Stained_Glass_JE3_BE3.png images/brown_stained_glass.png
mv images/Brown_Terracotta_JE1_BE1.png images/brown_terracotta.png
mv images/Brown_Wool_JE3_BE3.png images/brown_wool.png
mv images/Bubble_Coral_Block_JE2_BE1.png images/bubble_coral_block.png
mv images/Bubble_Coral_Fan_JE1_BE2.png images/bubble_coral_fan.png
mv images/Bubble_Coral_JE1_BE1.png images/bubble_coral.png
mv images/Budding_Amethyst_JE3_BE1.png images/budding_amethyst.png
mv images/Cactus_JE4.png images/cactus.png
mv images/Cake_JE4.png images/cake.png
mv images/Calcite_JE4_BE1.png images/calcite.png
mv images/Candle_JE1_BE1.png images/candle.png
mv images/Cartography_Table_JE3_BE2.png images/cartography_table.png
mv images/Cauldron_JE8.png images/cauldron.png
mv images/Cherry_Button_JE2.png images/cherry_button.png
mv images/Cherry_Door_JE2_BE1.png images/cherry_door.png
mv images/Cherry_Fence_Gate_JE1_BE1.png images/cherry_fence_gate.png
mv images/Cherry_Hanging_Sign_JE1_BE1.png images/cherry_hanging_sign.png
mv images/Cherry_Leaves_JE2.png images/cherry_leaves.png
mv images/Cherry_Planks_JE1_BE1.png images/cherry_planks.png
mv images/Cherry_Pressure_Plate_JE1_BE1.png images/cherry_pressure_plate.png
mv images/Cherry_Sapling_JE2.png images/cherry_sapling.png
mv images/Cherry_Slab_JE1_BE1.png images/cherry_slab.png
mv images/Cherry_Stairs_JE1_BE1.png images/cherry_stairs.png
mv images/Cherry_Trapdoor_JE1_BE1.png images/cherry_trapdoor.png
mv images/Chiseled_Copper_JE1_BE1.png images/chiseled_copper.png
mv images/Chiseled_Deepslate_JE2_BE1.png images/chiseled_deepslate.png
mv images/Chiseled_Nether_Bricks_JE3_BE3.png images/chiseled_nether_bricks.png
mv images/Chiseled_Polished_Blackstone_JE1_BE1.png images/chiseled_polished_blackstone.png
mv images/Chiseled_Red_Sandstone_JE4_BE2.png images/chiseled_red_sandstone.png
mv images/Chiseled_Resin_Bricks_JE2_BE3.png images/chiseled_resin_bricks.png
mv images/Chiseled_Sandstone_JE5_BE2.png images/chiseled_sandstone.png
mv images/Chiseled_Stone_Bricks_JE3_BE2.png images/chiseled_stone_bricks.png
mv images/Chiseled_Tuff_Bricks_JE1_BE1.png images/chiseled_tuff_bricks.png
mv images/Chiseled_Tuff_JE1_BE1.png images/chiseled_tuff.png
mv images/Chorus_Flower_JE2_BE2.png images/chorus_flower.png
mv images/Chorus_Plant_JE2_BE2.png images/chorus_plant.png
mv images/Clay_JE2_BE2.png images/clay.png
mv images/Closed_Eyeblossom_JE1_BE1.png images/closed_eyeblossom.png
mv images/Coal_Ore_JE5_BE4.png images/coal_ore.png
mv images/Coarse_Dirt.png images/coarse_dirt.png
mv images/Cobbled_Deepslate.png images/cobbled_deepslate.png
mv images/Cobbled_Deepslate_Slab_JE3.png images/cobbled_deepslate_slab.png
mv images/Cobbled_Deepslate_Stairs_JE3.png images/cobbled_deepslate_stairs.png
mv images/Cobbled_Deepslate_Wall_JE3.png images/cobbled_deepslate_wall.png
mv images/Cobblestone_JE5_BE3.png images/cobblestone.png
mv images/Cobblestone_Slab_JE4_BE3.png images/cobblestone_slab.png
mv images/Cobblestone_Wall_JE2_BE2.png images/cobblestone_wall.png
mv images/Cobweb_JE5.png images/cobweb.png
mv images/Composter_JE1.png images/composter.png
mv images/Conduit_JE1_BE1.png images/conduit.png
mv images/Copper_Block_JE1_BE1.png images/copper_block.png
mv images/Copper_Bulb_JE1_BE1.png images/copper_bulb.png
mv images/Copper_Door_JE3_BE3.png images/copper_door.png
mv images/Copper_Grate_JE1_BE1.png images/copper_grate.png
mv images/Copper_Ore_JE2_BE2.png images/copper_ore.png
mv images/Copper_Trapdoor_JE2_BE2.png images/copper_trapdoor.png
mv images/Cornflower_JE1_BE1.png images/cornflower.png
mv images/Cracked_Deepslate_Bricks_JE1_BE1.png images/cracked_deepslate_bricks.png
mv images/Cracked_Deepslate_Tiles_JE1_BE1.png images/cracked_deepslate_tiles.png
mv images/Cracked_Nether_Bricks_JE2_BE2.png images/cracked_nether_bricks.png
mv images/Cracked_Polished_Blackstone_Bricks_JE2_BE2.png images/cracked_polished_blackstone_bricks.png
mv images/Cracked_Stone_Bricks_JE3_BE2.png images/cracked_stone_bricks.png
mv images/Crafter_JE4_BE3.png images/crafter.png
mv images/Crafting_Table_JE4_BE3.png images/crafting_table.png
mv images/Creaking_Heart_JE2_BE2.png images/creaking_heart.png
mv images/Crimson_Button_JE2.png images/crimson_button.png
mv images/Crimson_Door_JE3.png images/crimson_door.png
mv images/Crimson_Fence_Gate_JE1_BE1.png images/crimson_fence_gate.png
mv images/Crimson_Fungus_JE1_BE1.png images/crimson_fungus.png
mv images/Crimson_Hanging_Sign_JE1_BE1.png images/crimson_hanging_sign.png
mv images/Crimson_Nylium_JE1_BE1.png images/crimson_nylium.png
mv images/Crimson_Planks_JE1_BE1.png images/crimson_planks.png
mv images/Crimson_Pressure_Plate_JE1_BE1.png images/crimson_pressure_plate.png
mv images/Crimson_Roots_JE1_BE1.png images/crimson_roots.png
mv images/Crimson_Slab_JE1_BE1.png images/crimson_slab.png
mv images/Crimson_Trapdoor_JE1_BE1.png images/crimson_trapdoor.png
mv images/Crying_Obsidian_JE1_BE1.png images/crying_obsidian.png
mv images/Cut_Copper_JE2_BE1.png images/cut_copper.png
mv images/Cut_Copper_Slab_JE2_BE1.png images/cut_copper_slab.png
mv images/Cut_Red_Sandstone_JE4_BE2.png images/cut_red_sandstone.png
mv images/Cut_Red_Sandstone_Slab_JE1_BE1.png images/cut_red_sandstone_slab.png
mv images/Cut_Sandstone_JE5_BE2.png images/cut_sandstone.png
mv images/Cut_Sandstone_Slab_JE1_BE1.png images/cut_sandstone_slab.png
mv images/Cyan_Bed.png images/cyan_bed.png
mv images/Cyan_Candle.png images/cyan_candle.png
mv images/Cyan_Carpet_JE2_BE2.png images/cyan_carpet.png
mv images/Cyan_Concrete.png images/cyan_concrete.png
mv images/Cyan_Concrete_Powder.png images/cyan_concrete_powder.png
mv images/Cyan_Shulker_Box_JE2_BE2.png images/cyan_shulker_box.png
mv images/Cyan_Stained_Glass_JE3_BE3.png images/cyan_stained_glass.png
mv images/Cyan_Terracotta_JE1_BE1.png images/cyan_terracotta.png
mv images/Cyan_Wool_JE3_BE3.png images/cyan_wool.png
mv images/Dandelion_JE8_BE2.png images/dandelion.png
mv images/Dark_Oak_Button_JE4.png images/dark_oak_button.png
mv images/Dark_Oak_Door_JE4.png images/dark_oak_door.png
mv images/Dark_Oak_Fence_Gate_JE3_BE2.png images/dark_oak_fence_gate.png
mv images/Dark_Oak_Hanging_Sign_JE1_BE1.png images/dark_oak_hanging_sign.png
mv images/Dark_Oak_Leaves.png images/dark_oak_leaves.png
mv images/Dark_Oak_Planks_JE3_BE2.png images/dark_oak_planks.png
mv images/Dark_Oak_Pressure_Plate_JE3_BE2.png images/dark_oak_pressure_plate.png
mv images/Dark_Oak_Sapling_JE7_BE2.png images/dark_oak_sapling.png
mv images/Dark_Oak_Slab_JE3_BE2.png images/dark_oak_slab.png
mv images/Dark_Oak_Trapdoor_JE1_BE1.png images/dark_oak_trapdoor.png
mv images/Dark_Prismarine_JE2_BE2.png images/dark_prismarine.png
mv images/Dark_Prismarine_Slab_JE2_BE2.png images/dark_prismarine_slab.png
mv images/Daylight_Detector_JE1_BE1.png images/daylight_detector.png
mv images/Dead_Brain_Coral_Block_JE2_BE1.png images/dead_brain_coral_block.png
mv images/Dead_Brain_Coral_Fan_JE1_BE2.png images/dead_brain_coral_fan.png
mv images/Dead_Brain_Coral_JE1_BE1.png images/dead_brain_coral.png
mv images/Dead_Bubble_Coral_Block_JE2_BE1.png images/dead_bubble_coral_block.png
mv images/Dead_Bubble_Coral_Fan_JE1_BE2.png images/dead_bubble_coral_fan.png
mv images/Dead_Bubble_Coral_JE1_BE1.png images/dead_bubble_coral.png
mv images/Dead_Bush_JE2_BE2.png images/dead_bush.png
mv images/Dead_Fire_Coral_Block_JE2_BE1.png images/dead_fire_coral_block.png
mv images/Dead_Fire_Coral_Fan_JE1_BE2.png images/dead_fire_coral_fan.png
mv images/Dead_Fire_Coral_JE1_BE1.png images/dead_fire_coral.png
mv images/Dead_Horn_Coral_Block_JE2_BE1.png images/dead_horn_coral_block.png
mv images/Dead_Horn_Coral_Fan_JE1_BE2.png images/dead_horn_coral_fan.png
mv images/Dead_Horn_Coral_JE1_BE1.png images/dead_horn_coral.png
mv images/Dead_Tube_Coral_Block_JE2_BE1.png images/dead_tube_coral_block.png
mv images/Dead_Tube_Coral_Fan_JE1_BE2.png images/dead_tube_coral_fan.png
mv images/Dead_Tube_Coral_JE1_BE1.png images/dead_tube_coral.png
mv images/Deepslate.png images/deepslate.png
mv images/Deepslate_Bricks_JE2_BE1.png images/deepslate_bricks.png
mv images/Deepslate_Brick_Slab_JE2.png images/deepslate_brick_slab.png
mv images/Deepslate_Brick_Stairs_JE2.png images/deepslate_brick_stairs.png
mv images/Deepslate_Brick_Wall_JE2.png images/deepslate_brick_wall.png
mv images/Deepslate_Coal_Ore_JE1_BE2.png images/deepslate_coal_ore.png
mv images/Deepslate_Copper_Ore_JE2_BE2.png images/deepslate_copper_ore.png
mv images/Deepslate_Diamond_Ore_JE2_BE1.png images/deepslate_diamond_ore.png
mv images/Deepslate_Emerald_Ore_JE1_BE1.png images/deepslate_emerald_ore.png
mv images/Deepslate_Gold_Ore_JE2_BE1.png images/deepslate_gold_ore.png
mv images/Deepslate_Iron_Ore_JE2_BE1.png images/deepslate_iron_ore.png
mv images/Deepslate_Redstone_Ore_JE2_BE1.png images/deepslate_redstone_ore.png
mv images/Deepslate_Tiles_JE2_BE1.png images/deepslate_tiles.png
mv images/Deepslate_Tile_Slab_JE2.png images/deepslate_tile_slab.png
mv images/Deepslate_Tile_Stairs_JE2.png images/deepslate_tile_stairs.png
mv images/Deepslate_Tile_Wall_JE2.png images/deepslate_tile_wall.png
mv images/Diamond_Ore_JE5_BE5.png images/diamond_ore.png
mv images/Diorite.png images/diorite.png
mv images/Diorite_Slab_JE3_BE2.png images/diorite_slab.png
mv images/Diorite_Wall_JE3_BE1.png images/diorite_wall.png
mv images/Dirt.png images/dirt.png
mv images/Dirt_Path_JE4_BE3.png images/dirt_path.png
mv images/Dragon_Egg_JE5.png images/dragon_egg.png
mv images/Dried_Kelp_Block_JE1_BE2.png images/dried_kelp_block.png
mv images/Dripstone_Block_JE1_BE1.png images/dripstone_block.png
mv images/Emerald_Ore_JE4_BE3.png images/emerald_ore.png
mv images/Enchanting_Table_JE4_BE2.png images/enchanting_table.png
mv images/Ender_Chest.png images/ender_chest.png
mv images/End_Stone_Bricks_JE2_BE2.png images/end_stone_bricks.png
mv images/End_Stone_Brick_Slab_JE1_BE2.png images/end_stone_brick_slab.png
mv images/End_Stone_Brick_Wall_JE1_BE2.png images/end_stone_brick_wall.png
mv images/End_Stone_JE3_BE2.png images/end_stone.png
mv images/Exposed_Chiseled_Copper_JE1_BE1.png images/exposed_chiseled_copper.png
mv images/Exposed_Copper_Bulb_JE1_BE1.png images/exposed_copper_bulb.png
mv images/Exposed_Copper_Door_JE3_BE3.png images/exposed_copper_door.png
mv images/Exposed_Copper_Grate_JE1_BE1.png images/exposed_copper_grate.png
mv images/Exposed_Copper_Trapdoor_JE2_BE2.png images/exposed_copper_trapdoor.png
mv images/Exposed_Cut_Copper_JE1_BE1.png images/exposed_cut_copper.png
mv images/Exposed_Cut_Copper_Slab_JE1_BE1.png images/exposed_cut_copper_slab.png
mv images/Farmland_JE4_BE6.png images/farmland.png
mv images/Fern.png images/fern.png
mv images/Fire_Coral_Block_JE2_BE1.png images/fire_coral_block.png
mv images/Fire_Coral_Fan_JE1_BE2.png images/fire_coral_fan.png
mv images/Fire_Coral_JE2_BE1.png images/fire_coral.png
mv images/Fletching_Table_JE2_BE1.png images/fletching_table.png
mv images/Flowering_Azalea_JE2_BE2.png images/flowering_azalea.png
mv images/Flowering_Azalea_Leaves.png images/flowering_azalea_leaves.png
mv images/Flower_Pot_JE3.png images/flower_pot.png
mv images/Frogspawn_JE1_BE2.png images/frogspawn.png
mv images/Gilded_Blackstone_JE2_BE2.png images/gilded_blackstone.png
mv images/Glass_JE4_BE2.png images/glass.png
mv images/Glowstone_JE4_BE2.png images/glowstone.png
mv images/Glow_Item_Frame_JE1_BE3.png images/glow_item_frame.png
mv images/Gold_Ore_JE7_BE4.png images/gold_ore.png
mv images/Granite.png images/granite.png
mv images/Granite_Slab_JE1_BE1.png images/granite_slab.png
mv images/Granite_Wall_JE1_BE1.png images/granite_wall.png
mv images/Grass_Block_JE7_BE6.png images/grass_block.png
mv images/Gravel_JE5_BE4.png images/gravel.png
mv images/Gray_Bed.png images/gray_bed.png
mv images/Gray_Candle.png images/gray_candle.png
mv images/Gray_Carpet_JE2_BE2.png images/gray_carpet.png
mv images/Gray_Concrete.png images/gray_concrete.png
mv images/Gray_Concrete_Powder.png images/gray_concrete_powder.png
mv images/Gray_Shulker_Box_JE2_BE2.png images/gray_shulker_box.png
mv images/Gray_Stained_Glass_JE3_BE3.png images/gray_stained_glass.png
mv images/Gray_Terracotta_JE1_BE1.png images/gray_terracotta.png
mv images/Gray_Wool_JE3_BE3.png images/gray_wool.png
mv images/Green_Bed.png images/green_bed.png
mv images/Green_Candle.png images/green_candle.png
mv images/Green_Carpet_JE2_BE2.png images/green_carpet.png
mv images/Green_Concrete.png images/green_concrete.png
mv images/Green_Concrete_Powder.png images/green_concrete_powder.png
mv images/Green_Shulker_Box_JE2_BE2.png images/green_shulker_box.png
mv images/Green_Stained_Glass_JE3_BE3.png images/green_stained_glass.png
mv images/Green_Terracotta_JE1_BE1.png images/green_terracotta.png
mv images/Green_Wool_JE3_BE3.png images/green_wool.png
mv images/Hanging_Roots_JE2_BE1.png images/hanging_roots.png
mv images/Heavy_Core_JE1_BE1.png images/heavy_core.png
mv images/Heavy_Weighted_Pressure_Plate_JE2_BE2.png images/heavy_weighted_pressure_plate.png
mv images/Honeycomb_Block_JE1_BE1.png images/honeycomb_block.png
mv images/Honey_Block_JE1_BE2.png images/honey_block.png
mv images/Horn_Coral_Block_JE2_BE2.png images/horn_coral_block.png
mv images/Horn_Coral_Fan_JE1_BE2.png images/horn_coral_fan.png
mv images/Horn_Coral_JE1_BE1.png images/horn_coral.png
mv images/Ice_JE4_BE6.png images/ice.png
mv images/Iron_Door_JE5.png images/iron_door.png
mv images/Iron_Ore_JE6_BE4.png images/iron_ore.png
mv images/Iron_Trapdoor_JE3_BE2.png images/iron_trapdoor.png
mv images/Item_Frame_JE2_BE2.png images/item_frame.png
mv images/Jukebox_JE2_BE2.png images/jukebox.png
mv images/Jungle_Button_JE4.png images/jungle_button.png
mv images/Jungle_Door_JE5.png images/jungle_door.png
mv images/Jungle_Fence_Gate_JE3_BE2.png images/jungle_fence_gate.png
mv images/Jungle_Hanging_Sign_JE1_BE1.png images/jungle_hanging_sign.png
mv images/Jungle_Leaves.png images/jungle_leaves.png
mv images/Jungle_Planks_JE3_BE2.png images/jungle_planks.png
mv images/Jungle_Pressure_Plate_JE3_BE2.png images/jungle_pressure_plate.png
mv images/Jungle_Sapling_JE7_BE2.png images/jungle_sapling.png
mv images/Jungle_Slab_JE3_BE2.png images/jungle_slab.png
mv images/Jungle_Trapdoor_JE1_BE1.png images/jungle_trapdoor.png
mv images/Large_Fern.png images/large_fern.png
mv images/Lectern_JE2_BE1.png images/lectern.png
mv images/Light_Blue_Bed.png images/light_blue_bed.png
mv images/Light_Blue_Candle.png images/light_blue_candle.png
mv images/Light_Blue_Carpet_JE2_BE2.png images/light_blue_carpet.png
mv images/Light_Blue_Concrete.png images/light_blue_concrete.png
mv images/Light_Blue_Concrete_Powder.png images/light_blue_concrete_powder.png
mv images/Light_Blue_Shulker_Box_JE2_BE2.png images/light_blue_shulker_box.png
mv images/Light_Blue_Stained_Glass_JE3_BE3.png images/light_blue_stained_glass.png
mv images/Light_Blue_Terracotta_JE1_BE1.png images/light_blue_terracotta.png
mv images/Light_Blue_Wool_JE3_BE3.png images/light_blue_wool.png
mv images/Light_Gray_Bed.png images/light_gray_bed.png
mv images/Light_Gray_Candle.png images/light_gray_candle.png
mv images/Light_Gray_Carpet_JE2_BE2.png images/light_gray_carpet.png
mv images/Light_Gray_Concrete.png images/light_gray_concrete.png
mv images/Light_Gray_Concrete_Powder.png images/light_gray_concrete_powder.png
mv images/Light_Gray_Shulker_Box_JE2_BE2.png images/light_gray_shulker_box.png
mv images/Light_Gray_Stained_Glass_JE3_BE3.png images/light_gray_stained_glass.png
mv images/Light_Gray_Terracotta_JE1_BE1.png images/light_gray_terracotta.png
mv images/Light_Gray_Wool_JE3_BE3.png images/light_gray_wool.png
mv images/Light_Weighted_Pressure_Plate_JE3_BE2.png images/light_weighted_pressure_plate.png
mv images/Lilac_JE4_BE2.png images/lilac.png
mv images/Lily_of_the_Valley_JE1_BE1.png images/lily_of_the_valley.png
mv images/Lily_Pad_JE2_BE2.png images/lily_pad.png
mv images/Lime_Bed.png images/lime_bed.png
mv images/Lime_Candle.png images/lime_candle.png
mv images/Lime_Carpet_JE2_BE2.png images/lime_carpet.png
mv images/Lime_Concrete.png images/lime_concrete.png
mv images/Lime_Concrete_Powder.png images/lime_concrete_powder.png
mv images/Lime_Shulker_Box_JE2_BE2.png images/lime_shulker_box.png
mv images/Lime_Stained_Glass_JE3_BE3.png images/lime_stained_glass.png
mv images/Lime_Terracotta_JE1_BE1.png images/lime_terracotta.png
mv images/Lime_Wool_JE3_BE3.png images/lime_wool.png
mv images/Lodestone_JE1_BE1.png images/lodestone.png
mv images/Magenta_Bed.png images/magenta_bed.png
mv images/Magenta_Candle.png images/magenta_candle.png
mv images/Magenta_Carpet_JE2_BE2.png images/magenta_carpet.png
mv images/Magenta_Concrete.png images/magenta_concrete.png
mv images/Magenta_Concrete_Powder.png images/magenta_concrete_powder.png
mv images/Magenta_Shulker_Box_JE2_BE2.png images/magenta_shulker_box.png
mv images/Magenta_Stained_Glass_JE3_BE3.png images/magenta_stained_glass.png
mv images/Magenta_Terracotta_JE1_BE1.png images/magenta_terracotta.png
mv images/Magenta_Wool_JE3_BE3.png images/magenta_wool.png
mv images/Magma_Block_JE2_BE2.png images/magma_block.png
mv images/Mangrove_Button_JE2.png images/mangrove_button.png
mv images/Mangrove_Door_JE1.png images/mangrove_door.png
mv images/Mangrove_Fence_Gate_JE1_BE1.png images/mangrove_fence_gate.png
mv images/Mangrove_Hanging_Sign_JE1_BE1.png images/mangrove_hanging_sign.png
mv images/Mangrove_Leaves.png images/mangrove_leaves.png
mv images/Mangrove_Planks_JE1_BE1.png images/mangrove_planks.png
mv images/Mangrove_Pressure_Plate_JE1_BE1.png images/mangrove_pressure_plate.png
mv images/Mangrove_Propagule_JE1_BE1.png images/mangrove_propagule.png
mv images/Mangrove_Roots_JE2.png images/mangrove_roots.png
mv images/Mangrove_Sign_JE1_BE1.png images/mangrove_sign.png
mv images/Mangrove_Slab_JE1_BE1.png images/mangrove_slab.png
mv images/Mangrove_Stairs_JE1_BE1.png images/mangrove_stairs.png
mv images/Mangrove_Trapdoor_JE1_BE1.png images/mangrove_trapdoor.png
mv images/Melon_JE2_BE2.png images/melon.png
mv images/Mossy_Cobblestone_JE4_BE2.png images/mossy_cobblestone.png
mv images/Mossy_Cobblestone_Slab_JE2_BE2.png images/mossy_cobblestone_slab.png
mv images/Mossy_Cobblestone_Wall_JE2_BE2.png images/mossy_cobblestone_wall.png
mv images/Mossy_Stone_Bricks_JE3_BE2.png images/mossy_stone_bricks.png
mv images/Mossy_Stone_Brick_Slab_JE2_BE2.png images/mossy_stone_brick_slab.png
mv images/Mossy_Stone_Brick_Wall_JE2_BE1.png images/mossy_stone_brick_wall.png
mv images/Moss_Block_JE1_BE1.png images/moss_block.png
mv images/Moss_Carpet.png images/moss_carpet.png
mv images/Muddy_Mangrove_Roots_JE1_BE1.png images/muddy_mangrove_roots.png
mv images/Mud_Bricks_JE1_BE1.png images/mud_bricks.png
mv images/Mud_Brick_Slab_JE1_BE1.png images/mud_brick_slab.png
mv images/Mud_Brick_Stairs_JE1_BE1.png images/mud_brick_stairs.png
mv images/Mud_Brick_Wall_JE1_BE1.png images/mud_brick_wall.png
mv images/Mud_JE1_BE1.png images/mud.png
mv images/Mycelium_JE5_BE3.png images/mycelium.png
mv images/Netherrack_JE4_BE2.png images/netherrack.png
mv images/Nether_Bricks_JE4_BE5.png images/nether_bricks.png
mv images/Nether_Brick_Slab_JE4_BE5.png images/nether_brick_slab.png
mv images/Nether_Brick_Wall_JE3_BE4.png images/nether_brick_wall.png
mv images/Nether_Gold_Ore_JE2_BE1.png images/nether_gold_ore.png
mv images/Nether_Quartz_Ore_JE3_BE2.png images/nether_quartz_ore.png
mv images/Nether_Sprouts_JE2_BE2.png images/nether_sprouts.png
mv images/Nether_Wart_Block_JE3.png images/nether_wart_block.png
mv images/Note_Block_JE2_BE2.png images/note_block.png
mv images/Oak_Button_JE5.png images/oak_button.png
mv images/Oak_Door_JE8.png images/oak_door.png
mv images/Oak_Fence_Gate_JE4_BE3.png images/oak_fence_gate.png
mv images/Oak_Fence_JE4_BE2.png images/oak_fence.png
mv images/Oak_Hanging_Sign_JE1_BE1.png images/oak_hanging_sign.png
mv images/Oak_Leaves.png images/oak_leaves.png
mv images/Oak_Planks.png images/oak_planks.png
mv images/Oak_Pressure_Plate_JE5_BE2.png images/oak_pressure_plate.png
mv images/Oak_Sapling_JE14.png images/oak_sapling.png
mv images/Oak_Slab_JE5_BE2.png images/oak_slab.png
mv images/Oak_Trapdoor_JE4_BE2.png images/oak_trapdoor.png
mv images/Observer_JE4_BE3.png images/observer.png
mv images/Obsidian_JE3_BE2.png images/obsidian.png
mv images/Open_Eyeblossom_JE1_BE1.png images/open_eyeblossom.png
mv images/Orange_Bed.png images/orange_bed.png
mv images/Orange_Candle.png images/orange_candle.png
mv images/Orange_Carpet_JE2_BE2.png images/orange_carpet.png
mv images/Orange_Concrete.png images/orange_concrete.png
mv images/Orange_Concrete_Powder.png images/orange_concrete_powder.png
mv images/Orange_Shulker_Box_JE2_BE2.png images/orange_shulker_box.png
mv images/Orange_Stained_Glass_JE3_BE3.png images/orange_stained_glass.png
mv images/Orange_Terracotta_JE1_BE1.png images/orange_terracotta.png
mv images/Orange_Tulip_JE7_BE2.png images/orange_tulip.png
mv images/Orange_Wool_JE3_BE3.png images/orange_wool.png
mv images/Oxeye_Daisy_JE7_BE2.png images/oxeye_daisy.png
mv images/Oxidized_Chiseled_Copper_JE1_BE1.png images/oxidized_chiseled_copper.png
mv images/Oxidized_Copper_Bulb_JE1_BE1.png images/oxidized_copper_bulb.png
mv images/Oxidized_Copper_Door_JE3_BE3.png images/oxidized_copper_door.png
mv images/Oxidized_Copper_Grate_JE1_BE1.png images/oxidized_copper_grate.png
mv images/Oxidized_Copper_Trapdoor_JE2_BE2.png images/oxidized_copper_trapdoor.png
mv images/Oxidized_Cut_Copper_JE1_BE1.png images/oxidized_cut_copper.png
mv images/Oxidized_Cut_Copper_Slab_JE1_BE1.png images/oxidized_cut_copper_slab.png
mv images/Packed_Ice_JE2_BE3.png images/packed_ice.png
mv images/Packed_Mud_JE1_BE1.png images/packed_mud.png
mv images/Pale_Hanging_Moss_JE1_BE1.png images/pale_hanging_moss.png
mv images/Pale_Moss_Block_JE1_BE1.png images/pale_moss_block.png
mv images/Pale_Moss_Carpet_JE1_BE1.png images/pale_moss_carpet.png
mv images/Pale_Oak_Button_JE1_BE1.png images/pale_oak_button.png
mv images/Pale_Oak_Door_JE1_BE1.png images/pale_oak_door.png
mv images/Pale_Oak_Fence_Gate_JE1_BE1.png images/pale_oak_fence_gate.png
mv images/Pale_Oak_Hanging_Sign_JE2_BE1.png images/pale_oak_hanging_sign.png
mv images/Pale_Oak_Leaves_JE1.png images/pale_oak_leaves.png
mv images/Pale_Oak_Planks_JE1_BE1.png images/pale_oak_planks.png
mv images/Pale_Oak_Pressure_Plate_JE1_BE1.png images/pale_oak_pressure_plate.png
mv images/Pale_Oak_Sapling_JE1_BE1.png images/pale_oak_sapling.png
mv images/Pale_Oak_Sign_JE1_BE1.png images/pale_oak_sign.png
mv images/Pale_Oak_Slab_JE1_BE1.png images/pale_oak_slab.png
mv images/Pale_Oak_Stairs_JE1_BE1.png images/pale_oak_stairs.png
mv images/Pale_Oak_Trapdoor_JE1_BE1.png images/pale_oak_trapdoor.png
mv images/Peony_JE4_BE3.png images/peony.png
mv images/Pink_Bed.png images/pink_bed.png
mv images/Pink_Candle.png images/pink_candle.png
mv images/Pink_Carpet_JE2_BE2.png images/pink_carpet.png
mv images/Pink_Concrete.png images/pink_concrete.png
mv images/Pink_Concrete_Powder.png images/pink_concrete_powder.png
mv images/Pink_Shulker_Box_JE2_BE2.png images/pink_shulker_box.png
mv images/Pink_Stained_Glass_JE3_BE3.png images/pink_stained_glass.png
mv images/Pink_Terracotta_JE1_BE1.png images/pink_terracotta.png
mv images/Pink_Tulip_JE7_BE2.png images/pink_tulip.png
mv images/Pink_Wool_JE3_BE3.png images/pink_wool.png
mv images/Pitcher_Plant_JE1_BE1.png images/pitcher_plant.png
mv images/Podzol_JE2_BE2.png images/podzol.png
mv images/Polished_Andesite_JE2_BE2.png images/polished_andesite.png
mv images/Polished_Andesite_Slab_JE2_BE2.png images/polished_andesite_slab.png
mv images/Polished_Blackstone_Bricks_JE2_BE2.png images/polished_blackstone_bricks.png
mv images/Polished_Blackstone_Brick_Slab_JE1_BE1.png images/polished_blackstone_brick_slab.png
mv images/Polished_Blackstone_Brick_Wall_JE2.png images/polished_blackstone_brick_wall.png
mv images/Polished_Blackstone_Button_JE2.png images/polished_blackstone_button.png
mv images/Polished_Blackstone_JE1_BE1.png images/polished_blackstone.png
mv images/Polished_Blackstone_Pressure_Plate_JE1_BE1.png images/polished_blackstone_pressure_plate.png
mv images/Polished_Blackstone_Slab_JE1_BE1.png images/polished_blackstone_slab.png
mv images/Polished_Blackstone_Wall_JE1_BE1.png images/polished_blackstone_wall.png
mv images/Polished_Deepslate_JE2_BE1.png images/polished_deepslate.png
mv images/Polished_Deepslate_Slab_JE2.png images/polished_deepslate_slab.png
mv images/Polished_Deepslate_Stairs_JE2.png images/polished_deepslate_stairs.png
mv images/Polished_Deepslate_Wall_JE2.png images/polished_deepslate_wall.png
mv images/Polished_Diorite_JE2_BE2.png images/polished_diorite.png
mv images/Polished_Diorite_Slab_JE2_BE2.png images/polished_diorite_slab.png
mv images/Polished_Granite_JE2_BE2.png images/polished_granite.png
mv images/Polished_Granite_Slab_JE1_BE1.png images/polished_granite_slab.png
mv images/Polished_Tuff_JE1_BE1.png images/polished_tuff.png
mv images/Polished_Tuff_Slab_JE1_BE1.png images/polished_tuff_slab.png
mv images/Polished_Tuff_Stairs_JE1_BE1.png images/polished_tuff_stairs.png
mv images/Polished_Tuff_Wall_JE1_BE1.png images/polished_tuff_wall.png
mv images/Poppy_JE8_BE2.png images/poppy.png
mv images/Prismarine_Bricks_JE2_BE2.png images/prismarine_bricks.png
mv images/Prismarine_Brick_Slab_JE2_BE2.png images/prismarine_brick_slab.png
mv images/Purple_Bed.png images/purple_bed.png
mv images/Purple_Candle.png images/purple_candle.png
mv images/Purple_Carpet_JE2_BE2.png images/purple_carpet.png
mv images/Purple_Concrete.png images/purple_concrete.png
mv images/Purple_Concrete_Powder.png images/purple_concrete_powder.png
mv images/Purple_Shulker_Box_JE4_BE2.png images/purple_shulker_box.png
mv images/Purple_Stained_Glass_JE3_BE3.png images/purple_stained_glass.png
mv images/Purple_Terracotta_JE1_BE1.png images/purple_terracotta.png
mv images/Purple_Wool_JE3_BE3.png images/purple_wool.png
mv images/Purpur_Block_JE2_BE2.png images/purpur_block.png
mv images/Purpur_Slab_JE2_BE2.png images/purpur_slab.png
mv images/Quartz_Bricks_JE2.png images/quartz_bricks.png
mv images/Quartz_Slab_JE3_BE3.png images/quartz_slab.png
mv images/Redstone_Lamp_JE3_BE2.png images/redstone_lamp.png
mv images/Redstone_Ore_JE4_BE3.png images/redstone_ore.png
mv images/Redstone_Torch_JE5.png images/redstone_torch.png
mv images/Red_Candle.png images/red_candle.png
mv images/Red_Carpet_JE2_BE2.png images/red_carpet.png
mv images/Red_Concrete.png images/red_concrete.png
mv images/Red_Concrete_Powder.png images/red_concrete_powder.png
mv images/Red_Mushroom_JE9.png images/red_mushroom.png
mv images/Red_Nether_Bricks_JE4_BE3.png images/red_nether_bricks.png
mv images/Red_Nether_Brick_Slab_JE3_BE3.png images/red_nether_brick_slab.png
mv images/Red_Nether_Brick_Wall_JE3_BE3.png images/red_nether_brick_wall.png
mv images/Red_Sandstone_JE4_BE2.png images/red_sandstone.png
mv images/Red_Sandstone_Slab_JE4_BE2.png images/red_sandstone_slab.png
mv images/Red_Sandstone_Wall_JE2_BE1.png images/red_sandstone_wall.png
mv images/Red_Sand_JE3_BE2.png images/red_sand.png
mv images/Red_Shulker_Box_JE2_BE2.png images/red_shulker_box.png
mv images/Red_Stained_Glass_JE4_BE4.png images/red_stained_glass.png
mv images/Red_Terracotta_JE1_BE1.png images/red_terracotta.png
mv images/Red_Tulip_JE7_BE2.png images/red_tulip.png
mv images/Red_Wool_JE3_BE3.png images/red_wool.png
mv images/Reinforced_Deepslate_JE1.png images/reinforced_deepslate.png
mv images/Resin_Bricks_JE1_BE2.png images/resin_bricks.png
mv images/Resin_Brick_Slab_JE1_BE2.png images/resin_brick_slab.png
mv images/Resin_Brick_Stairs_JE1_BE2.png images/resin_brick_stairs.png
mv images/Resin_Brick_Wall_JE1_BE2.png images/resin_brick_wall.png
mv images/Resin_Clump_JE1_BE1.png images/resin_clump.png
mv images/Rooted_Dirt_JE1_BE1.png images/rooted_dirt.png
mv images/Rose_Bush_JE4_BE3.png images/rose_bush.png
mv images/Sandstone_JE6_BE3.png images/sandstone.png
mv images/Sandstone_Slab_JE5_BE6.png images/sandstone_slab.png
mv images/Sandstone_Wall_JE2_BE1.png images/sandstone_wall.png
mv images/Sand_JE5_BE3.png images/sand.png
mv images/Sculk_Catalyst_JE1_BE1.png images/sculk_catalyst.png
mv images/Short_Grass.png images/short_grass.png
mv images/Shroomlight_JE1_BE1.png images/shroomlight.png
mv images/Shulker_Box_JE1_BE1.png images/shulker_box.png
mv images/Slime_Block_JE2_BE3.png images/slime_block.png
mv images/Small_Dripleaf_JE4.png images/small_dripleaf.png
mv images/Smithing_Table_JE2_BE2.png images/smithing_table.png
mv images/Smooth_Basalt_JE1_BE1.png images/smooth_basalt.png
mv images/Smooth_Quartz_Slab_JE2_BE2.png images/smooth_quartz_slab.png
mv images/Smooth_Red_Sandstone_JE4_BE2.png images/smooth_red_sandstone.png
mv images/Smooth_Red_Sandstone_Slab_JE3_BE2.png images/smooth_red_sandstone_slab.png
mv images/Smooth_Sandstone_JE7_BE2.png images/smooth_sandstone.png
mv images/Smooth_Sandstone_Slab_JE3_BE2.png images/smooth_sandstone_slab.png
mv images/Smooth_Stone_JE2_BE2.png images/smooth_stone.png
mv images/Smooth_Stone_Slab_JE2_BE2.png images/smooth_stone_slab.png
mv images/Sniffer_Egg_JE1_BE1.png images/sniffer_egg.png
mv images/Snow_Block_JE2_BE2.png images/snow_block.png
mv images/Soul_Sand_JE2_BE2.png images/soul_sand.png
mv images/Soul_Soil_JE1_BE1.png images/soul_soil.png
mv images/Soul_Torch_JE1.png images/soul_torch.png
mv images/Sponge_JE3_BE3.png images/sponge.png
mv images/Spore_Blossom_JE1.png images/spore_blossom.png
mv images/Spruce_Button_JE5.png images/spruce_button.png
mv images/Spruce_Door_JE4.png images/spruce_door.png
mv images/Spruce_Fence_Gate_JE4_BE2.png images/spruce_fence_gate.png
mv images/Spruce_Hanging_Sign_JE1_BE1.png images/spruce_hanging_sign.png
mv images/Spruce_Leaves.png images/spruce_leaves.png
mv images/Spruce_Planks_JE4_BE2.png images/spruce_planks.png
mv images/Spruce_Pressure_Plate_JE4_BE2.png images/spruce_pressure_plate.png
mv images/Spruce_Sapling_JE7_BE2.png images/spruce_sapling.png
mv images/Spruce_Slab_JE4_BE2.png images/spruce_slab.png
mv images/Spruce_Trapdoor_JE2_BE2.png images/spruce_trapdoor.png
mv images/Stone_Bricks_JE3_BE2.png images/stone_bricks.png
mv images/Stone_Brick_Slab_JE3_BE2.png images/stone_brick_slab.png
mv images/Stone_Brick_Wall_JE2_BE1.png images/stone_brick_wall.png
mv images/Stone_Button_JE6.png images/stone_button.png
mv images/Stone_JE8.png images/stone.png
mv images/Stone_Pressure_Plate_JE5_BE2.png images/stone_pressure_plate.png
mv images/Stone_Slab_JE2_BE1.png images/stone_slab.png
mv images/Structure_Block_JE2_BE1.png images/structure_block.png
mv images/Sugar_Cane.png images/sugar_cane.png
mv images/Sunflower_JE2_BE2.png images/sunflower.png
mv images/Tall_Grass.png images/tall_grass.png
mv images/Target_JE1_BE1.png images/target.png
mv images/Terracotta_JE2_BE2.png images/terracotta.png
mv images/Tinted_Glass_JE2_BE1.png images/tinted_glass.png
mv images/Torchflower_JE1_BE1.png images/torchflower.png
mv images/Torch_JE7.png images/torch.png
mv images/Trapped_Chest.png images/trapped_chest.png
mv images/Trial_Spawner_JE4_BE3.png images/trial_spawner.png
mv images/Tube_Coral_Block_JE2_BE1.png images/tube_coral_block.png
mv images/Tube_Coral_Fan_JE1_BE2.png images/tube_coral_fan.png
mv images/Tube_Coral_JE1_BE1.png images/tube_coral.png
mv images/Tuff.png images/tuff.png
mv images/Tuff_Bricks_JE3_BE3.png images/tuff_bricks.png
mv images/Tuff_Brick_Slab_JE3_BE3.png images/tuff_brick_slab.png
mv images/Tuff_Brick_Stairs_JE3_BE3.png images/tuff_brick_stairs.png
mv images/Tuff_Brick_Wall_JE3_BE3.png images/tuff_brick_wall.png
mv images/Tuff_Slab_JE1_BE1.png images/tuff_slab.png
mv images/Tuff_Stairs_JE1_BE1.png images/tuff_stairs.png
mv images/Tuff_Wall_JE1_BE1.png images/tuff_wall.png
mv images/Twisting_Vines_JE1_BE1.png images/twisting_vines.png
mv images/Vault_JE6_BE5.png images/vault.png
mv images/Warped_Button_JE2.png images/warped_button.png
mv images/Warped_Door_JE3.png images/warped_door.png
mv images/Warped_Fence_Gate_JE1_BE1.png images/warped_fence_gate.png
mv images/Warped_Fungus_JE1_BE1.png images/warped_fungus.png
mv images/Warped_Hanging_Sign_JE1_BE1.png images/warped_hanging_sign.png
mv images/Warped_Nylium_JE1_BE1.png images/warped_nylium.png
mv images/Warped_Planks_JE1_BE1.png images/warped_planks.png
mv images/Warped_Pressure_Plate_JE1_BE1.png images/warped_pressure_plate.png
mv images/Warped_Roots_JE1_BE1.png images/warped_roots.png
mv images/Warped_Slab_JE1_BE1.png images/warped_slab.png
mv images/Warped_Trapdoor_JE1_BE1.png images/warped_trapdoor.png
mv images/Warped_Wart_Block_JE1_BE1.png images/warped_wart_block.png
mv images/Weathered_Chiseled_Copper_JE1_BE1.png images/weathered_chiseled_copper.png
mv images/Weathered_Copper_Bulb_JE1_BE1.png images/weathered_copper_bulb.png
mv images/Weathered_Copper_Door_JE3_BE3.png images/weathered_copper_door.png
mv images/Weathered_Copper_Grate_JE1_BE1.png images/weathered_copper_grate.png
mv images/Weathered_Copper_Trapdoor_JE2_BE2.png images/weathered_copper_trapdoor.png
mv images/Weathered_Cut_Copper_JE1_BE1.png images/weathered_cut_copper.png
mv images/Weathered_Cut_Copper_Slab_JE1_BE1.png images/weathered_cut_copper_slab.png
mv images/Weeping_Vines_JE1.png images/weeping_vines.png
mv images/Wet_Sponge_JE2_BE2.png images/wet_sponge.png
mv images/White_Candle.png images/white_candle.png
mv images/White_Carpet_JE2_BE2.png images/white_carpet.png
mv images/White_Concrete.png images/white_concrete.png
mv images/White_Concrete_Powder.png images/white_concrete_powder.png
mv images/White_Shulker_Box_JE2_BE2.png images/white_shulker_box.png
mv images/White_Stained_Glass_JE3_BE3.png images/white_stained_glass.png
mv images/White_Terracotta_JE1_BE1.png images/white_terracotta.png
mv images/White_Tulip_JE7_BE2.png images/white_tulip.png
mv images/White_Wool_JE2_BE2.png images/white_wool.png
mv images/Wither_Rose_JE1_BE1.png images/wither_rose.png
mv images/Yellow_Bed.png images/yellow_bed.png
mv images/Yellow_Candle.png images/yellow_candle.png
mv images/Yellow_Carpet_JE2_BE2.png images/yellow_carpet.png
mv images/Yellow_Concrete.png images/yellow_concrete.png
mv images/Yellow_Concrete_Powder.png images/yellow_concrete_powder.png
mv images/Yellow_Shulker_Box_JE2_BE2.png images/yellow_shulker_box.png
mv images/Yellow_Stained_Glass_JE3_BE3.png images/yellow_stained_glass.png
mv images/Yellow_Terracotta_JE1_BE1.png images/yellow_terracotta.png
mv images/Yellow_Wool_JE3_BE3.png images/yellow_wool.png